/**
 * Preset layouts (remote templates) — pure data, no behavior.
 * Typed loosely against PresetDefinition; the item lists themselves are
 * cast to Item[] because the literal string narrowing would require
 * `as const` on every entry.
 */

import type { Item, PresetDefinition } from './types';

// Media player feature bitmask (used by editor's _buildMediaPlayerItems).
export const MP_FEATURE = {
  PAUSE: 1,
  SEEK: 2,
  VOLUME_SET: 4,
  VOLUME_MUTE: 8,
  PREVIOUS_TRACK: 16,
  NEXT_TRACK: 32,
  TURN_ON: 128,
  TURN_OFF: 256,
  VOLUME_STEP: 1024,
  SELECT_SOURCE: 2048,
  STOP: 4096,
  PLAY: 16384,
  SHUFFLE_SET: 32768,
  REPEAT_SET: 262144,
} as const;

export const DEFAULT_ITEMS: Item[] = [
  { type: 'button', row: 0, col: 0, icon: 'mdi:power' },
  { type: 'numbers', row: 0, col: 1, icon: 'mdi:dialpad' },
  { type: 'source', row: 0, col: 2, icon: 'mdi:import' },
  { type: 'dpad', row: 1, col: 0 },
  { type: 'button', row: 4, col: 0, icon: 'mdi:arrow-u-left-top' },
  { type: 'button', row: 4, col: 1, icon: 'mdi:home' },
  { type: 'button', row: 4, col: 2, icon: 'mdi:menu' },
  { type: 'button', row: 5, col: 0, icon: 'mdi:rewind', hold_repeat: true },
  { type: 'button', row: 5, col: 1, icon: 'mdi:play-pause' },
  { type: 'button', row: 5, col: 2, icon: 'mdi:fast-forward', hold_repeat: true },
  { type: 'button', variant: 'pill_top', row: 6, col: 0, icon: 'mdi:plus', hold_repeat: true },
  { type: 'button', row: 6, col: 1, text: 'GUIDE' },
  { type: 'button', variant: 'pill_top', row: 6, col: 2, icon: 'mdi:chevron-up', hold_repeat: true },
  { type: 'button', variant: 'pill_bottom', row: 7, col: 0, icon: 'mdi:minus', hold_repeat: true },
  { type: 'button', row: 7, col: 1, icon: 'mdi:volume-off' },
  { type: 'button', variant: 'pill_bottom', row: 7, col: 2, icon: 'mdi:chevron-down', hold_repeat: true },
  { type: 'color_buttons', row: 8, col: 0 },
];

export const REMOTE_PRESETS: Record<string, PresetDefinition> = {
  default: {
    label: 'Standard (9x3)',
    icon: 'mdi:remote',
    columns: 3,
    rows: 9,
    items: DEFAULT_ITEMS,
  },
  default_4col: {
    label: 'Standard (10x4)',
    icon: 'mdi:remote',
    columns: 4,
    rows: 10,
    items: [
      { type: 'button', row: 0, col: 0, icon: 'mdi:power' },
      { type: 'numbers', row: 8, col: 1, icon: 'mdi:dialpad', col_span: 2 },
      { type: 'source', row: 0, col: 3, icon: 'mdi:import' },
      { type: 'dpad', row: 1, col: 0, col_span: 4, row_span: 4 },
      { type: 'button', row: 5, col: 0, icon: 'mdi:arrow-u-left-top' },
      { type: 'button', row: 5, col: 1, icon: 'mdi:home' },
      { type: 'button', row: 5, col: 2, icon: 'mdi:information-outline' },
      { type: 'button', row: 5, col: 3, icon: 'mdi:menu' },
      { type: 'button', row: 6, col: 0, icon: 'mdi:rewind', hold_repeat: true },
      { type: 'button', row: 6, col: 1, icon: 'mdi:play-pause' },
      { type: 'button', row: 6, col: 2, icon: 'mdi:stop' },
      { type: 'button', row: 6, col: 3, icon: 'mdi:fast-forward', hold_repeat: true },
      { type: 'button', variant: 'pill_top', row: 7, col: 0, icon: 'mdi:plus', hold_repeat: true },
      { type: 'button', row: 7, col: 1, icon: 'mdi:volume-off' },
      { type: 'button', row: 7, col: 2, text: 'GUIDE' },
      { type: 'button', variant: 'pill_top', row: 7, col: 3, icon: 'mdi:chevron-up', hold_repeat: true },
      { type: 'button', variant: 'pill_bottom', row: 8, col: 0, icon: 'mdi:minus', hold_repeat: true },
      { type: 'button', variant: 'pill_bottom', row: 8, col: 3, icon: 'mdi:chevron-down', hold_repeat: true },
      { type: 'color_buttons', row: 9, col: 0, col_span: 4 },
    ],
  },
  media_player: {
    label: 'Media Player',
    icon: 'mdi:cast-audio',
    entity_domain: 'media_player',
    entity_label: 'Media Player',
    dynamic: true,
  },
  lg_webos: {
    label: 'LG TV (WebOS)',
    icon: 'mdi:television',
    entity_domain: 'media_player',
    entity_integration: 'webostv',
    entity_label: 'LG TV Media Player',
    columns: 3,
    rows: 11,
    items: [
      { type: 'button', row: 0, col: 0, icon: 'mdi:power',
        tap_action: { action: 'perform-action', perform_action: 'media_player.turn_off' } },
      { type: 'numbers', row: 0, col: 1, icon: 'mdi:dialpad',
        buttons: {
          '0': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '0' } } },
          '1': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '1' } } },
          '2': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '2' } } },
          '3': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '3' } } },
          '4': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '4' } } },
          '5': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '5' } } },
          '6': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '6' } } },
          '7': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '7' } } },
          '8': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '8' } } },
          '9': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: '9' } } },
          'dash':  { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'DASH' } } },
          'enter': { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'ENTER' } } },
        } },
      { type: 'source', row: 0, col: 2, icon: 'mdi:import' },
      { type: 'media', row: 1, col: 0 },
      { type: 'dpad', row: 3, col: 0,
        buttons: {
          up:    { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'UP' } } },
          down:  { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'DOWN' } } },
          left:  { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'LEFT' } } },
          right: { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'RIGHT' } } },
          ok:    { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'ENTER' } } },
        } },
      { type: 'button', row: 6, col: 0, icon: 'mdi:arrow-u-left-top',
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'BACK' } } },
      { type: 'button', row: 6, col: 1, icon: 'mdi:home',
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'HOME' } } },
      { type: 'button', row: 6, col: 2, icon: 'mdi:cog',
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'MENU' } } },
      { type: 'button', row: 7, col: 0, icon: 'mdi:skip-previous',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_previous_track' } },
      { type: 'button', row: 7, col: 1, icon: 'mdi:play-pause',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_play_pause' } },
      { type: 'button', row: 7, col: 2, icon: 'mdi:skip-next',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_next_track' } },
      { type: 'button', variant: 'pill_top', row: 8, col: 0, icon: 'mdi:plus', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'VOLUMEUP' } } },
      { type: 'button', row: 8, col: 1, text: 'GUIDE',
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'GUIDE' } } },
      { type: 'button', variant: 'pill_top', row: 8, col: 2, icon: 'mdi:chevron-up', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'CHANNELUP' } } },
      { type: 'button', variant: 'pill_bottom', row: 9, col: 0, icon: 'mdi:minus', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'VOLUMEDOWN' } } },
      { type: 'button', row: 9, col: 1, icon: 'mdi:volume-off',
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'MUTE' } } },
      { type: 'button', variant: 'pill_bottom', row: 9, col: 2, icon: 'mdi:chevron-down', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'CHANNELDOWN' } } },
      { type: 'color_buttons', row: 10, col: 0,
        buttons: {
          red:    { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'RED' } } },
          green:  { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'GREEN' } } },
          yellow: { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'YELLOW' } } },
          blue:   { tap_action: { action: 'perform-action', perform_action: 'webostv.button', data: { button: 'BLUE' } } },
        } },
    ],
  },
  samsung_tv: {
    label: 'Samsung TV',
    icon: 'mdi:television',
    entity_domain: 'remote',
    entity_integration: 'samsungtv',
    entity_label: 'Samsung TV Remote',
    columns: 3,
    rows: 11,
    items: [
      { type: 'button', row: 0, col: 0, icon: 'mdi:power',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_POWER' } } },
      { type: 'numbers', row: 0, col: 1, icon: 'mdi:dialpad',
        buttons: {
          '0': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_0' } } },
          '1': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_1' } } },
          '2': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_2' } } },
          '3': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_3' } } },
          '4': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_4' } } },
          '5': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_5' } } },
          '6': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_6' } } },
          '7': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_7' } } },
          '8': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_8' } } },
          '9': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_9' } } },
          'dash':  { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_DASH' } } },
          'enter': { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_ENTER' } } },
        } },
      { type: 'button', row: 0, col: 2, icon: 'mdi:import',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_SOURCE' } } },
      { type: 'media', row: 1, col: 0 },
      { type: 'dpad', row: 3, col: 0,
        buttons: {
          up:    { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_UP' } } },
          down:  { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_DOWN' } } },
          left:  { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_LEFT' } } },
          right: { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_RIGHT' } } },
          ok:    { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_ENTER' } } },
        } },
      { type: 'button', row: 6, col: 0, icon: 'mdi:arrow-u-left-top',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_RETURN' } } },
      { type: 'button', row: 6, col: 1, icon: 'mdi:home',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_HOME' } } },
      { type: 'button', row: 6, col: 2, icon: 'mdi:cog',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_MENU' } } },
      { type: 'button', row: 7, col: 0, icon: 'mdi:skip-previous',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_REWIND' } } },
      { type: 'button', row: 7, col: 1, icon: 'mdi:play-pause',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_PLAY' } } },
      { type: 'button', row: 7, col: 2, icon: 'mdi:skip-next',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_FF' } } },
      { type: 'button', variant: 'pill_top', row: 8, col: 0, icon: 'mdi:plus', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_VOLUP' } } },
      { type: 'button', row: 8, col: 1, icon: 'mdi:television-guide',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_GUIDE' } } },
      { type: 'button', variant: 'pill_top', row: 8, col: 2, icon: 'mdi:chevron-up', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_CHUP' } } },
      { type: 'button', variant: 'pill_bottom', row: 9, col: 0, icon: 'mdi:minus', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_VOLDOWN' } } },
      { type: 'button', row: 9, col: 1, icon: 'mdi:volume-off',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_MUTE' } } },
      { type: 'button', variant: 'pill_bottom', row: 9, col: 2, icon: 'mdi:chevron-down', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_CHDOWN' } } },
      { type: 'color_buttons', row: 10, col: 0,
        buttons: {
          red:    { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_RED' } } },
          green:  { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_GREEN' } } },
          yellow: { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_YELLOW' } } },
          blue:   { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'KEY_CYAN' } } },
        } },
    ],
  },
  apple_tv: {
    label: 'Apple TV',
    icon: 'mdi:apple',
    entity_domain: 'remote',
    entity_integration: 'apple_tv',
    entity_label: 'Apple TV Remote',
    columns: 3,
    rows: 10,
    items: [
      { type: 'button', row: 0, col: 0, icon: 'mdi:power',
        tap_action: { action: 'perform-action', perform_action: 'remote.toggle' } },
      { type: 'media', row: 1, col: 0 },
      { type: 'dpad', row: 3, col: 0,
        buttons: {
          up:    { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'up' } } },
          down:  { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'down' } } },
          left:  { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'left' } } },
          right: { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'right' } } },
          ok:    { tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'select' } } },
        } },
      { type: 'button', row: 6, col: 0, icon: 'mdi:arrow-u-left-top',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'menu' } } },
      { type: 'button', row: 6, col: 1, icon: 'mdi:home',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'home' } } },
      { type: 'button', row: 6, col: 2, icon: 'mdi:television',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'top_menu' } } },
      { type: 'button', row: 7, col: 0, icon: 'mdi:skip-previous',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'previous' } } },
      { type: 'button', row: 7, col: 1, icon: 'mdi:play-pause',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'play_pause' } } },
      { type: 'button', row: 7, col: 2, icon: 'mdi:skip-next',
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'next' } } },
      { type: 'button', variant: 'pill_top', row: 8, col: 1, icon: 'mdi:plus', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'volume_up' } } },
      { type: 'button', variant: 'pill_bottom', row: 9, col: 1, icon: 'mdi:minus', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'remote.send_command', data: { command: 'volume_down' } } },
    ],
  },
  spotify: {
    label: 'Spotify',
    icon: 'mdi:spotify',
    entity_domain: 'media_player',
    entity_integration: 'spotify',
    entity_label: 'Spotify Player',
    columns: 3,
    rows: 5,
    items: [
      { type: 'media', row: 0, col: 0 },
      { type: 'button', row: 2, col: 0, icon: 'mdi:skip-previous',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_previous_track' } },
      { type: 'button', row: 2, col: 1, icon: 'mdi:play-pause',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_play_pause' } },
      { type: 'button', row: 2, col: 2, icon: 'mdi:skip-next',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_next_track' } },
      { type: 'button', row: 3, col: 0, icon: 'mdi:shuffle-variant',
        tap_action: { action: 'perform-action', perform_action: 'media_player.shuffle_set' } },
      { type: 'source', row: 3, col: 1, icon: 'mdi:speaker-multiple' },
      { type: 'button', row: 3, col: 2, icon: 'mdi:repeat',
        tap_action: { action: 'perform-action', perform_action: 'media_player.repeat_set' } },
      { type: 'slider', row: 4, col: 0, col_span: 3, show_icon: true,
        slider_attribute: 'volume_level' },
    ],
  },
  unfolded_circle: {
    label: 'Unfolded Circle',
    icon: 'mdi:remote-tv',
    entity_domain: 'media_player',
    entity_integration: 'unfoldedcircle',
    entity_label: 'Media Player',
    secondary_entity_domain: 'remote',
    secondary_entity_integration: 'unfoldedcircle',
    secondary_entity_label: 'Remote',
    columns: 3,
    rows: 10,
    items: [
      { type: 'button', row: 0, col: 0, icon: 'mdi:power',
        tap_action: { action: 'perform-action', perform_action: 'media_player.toggle' } },
      { type: 'source', row: 0, col: 2, icon: 'mdi:import' },
      { type: 'media', row: 1, col: 0 },
      { type: 'dpad', row: 3, col: 0, _secondary: true,
        buttons: {
          up:    { tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'DPAD_UP' } } },
          down:  { tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'DPAD_DOWN' } } },
          left:  { tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'DPAD_LEFT' } } },
          right: { tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'DPAD_RIGHT' } } },
          ok:    { tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'DPAD_MIDDLE' } } },
        } },
      { type: 'button', row: 6, col: 0, icon: 'mdi:arrow-u-left-top', _secondary: true,
        tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'BACK' } } },
      { type: 'button', row: 6, col: 1, icon: 'mdi:home', _secondary: true,
        tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'HOME' } } },
      { type: 'button', row: 7, col: 0, icon: 'mdi:skip-previous',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_previous_track' } },
      { type: 'button', row: 7, col: 1, icon: 'mdi:play-pause',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_play_pause' } },
      { type: 'button', row: 7, col: 2, icon: 'mdi:skip-next',
        tap_action: { action: 'perform-action', perform_action: 'media_player.media_next_track' } },
      { type: 'button', variant: 'pill_top', row: 8, col: 0, icon: 'mdi:plus', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'media_player.volume_up' } },
      { type: 'button', row: 8, col: 1, icon: 'mdi:volume-off',
        tap_action: { action: 'perform-action', perform_action: 'media_player.volume_mute', data: { is_volume_muted: true } } },
      { type: 'button', variant: 'pill_top', row: 8, col: 2, icon: 'mdi:chevron-up', hold_repeat: true, _secondary: true,
        tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'CHANNEL_UP' } } },
      { type: 'button', variant: 'pill_bottom', row: 9, col: 0, icon: 'mdi:minus', hold_repeat: true,
        tap_action: { action: 'perform-action', perform_action: 'media_player.volume_down' } },
      { type: 'button', variant: 'pill_bottom', row: 9, col: 2, icon: 'mdi:chevron-down', hold_repeat: true, _secondary: true,
        tap_action: { action: 'perform-action', perform_action: 'unfoldedcircle.send_button_command', data: { command: 'CHANNEL_DOWN' } } },
    ],
  },
};
